server.forward-headers-strategy=framework
# app
app.allow.origins=${APP_ALLOW_ORIGINS}
# redis
spring.data.redis.url=${REDIS_URL}
# Kafka broker address
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
# Facebook APP API
facebook.app-id=${FACEBOOK_APP_ID}
facebook.app-secret=${FACEBOOK_APP_SECRET}
facebook.graph-host=https://graph.facebook.com
facebook.graph-version=v24.0
facebook.redirect-uri=${FACEBOOK_REDIRECT_URI}
facebook.verify-token=${FACEBOOK_VERIFY_TOKEN}
# mysql db
spring.datasource.url=${MYSQL_DB_URL}
spring.datasource.username=${MYSQL_DB_USERNAME}
spring.datasource.password=${MYSQL_DB_PASSWORD}
